# Generated by Django 3.1.3 on 2022-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='status_photo',
        ),
    ]
